###회원가입 성공 - 두 번 시도하면 customException 반환
POST http://localhost:8081/register
Content-Type: application/json

{
  "userEmail": "zerobase@gmail.com",
  "password": "1234",
  "username": "zerobase",
  "phoneNumber": "01012345678"
}