###회원가입 성공 - 두 번 시도하면 customException 반환
POST http://localhost:8081/register
Content-Type: application/json

{
  "userEmail": "zerobase3@gmail.com",
  "password": "1234",
  "username": "zerobase",
  "phoneNumber": "01012345678"
}

###로그인 성공
POST http://localhost:8081/login
Content-Type: application/json

{
  "userEmail": "zerobase3@gmail.com",
  "password": "1234"
}

###로그인 실패 - 이메일 틀림
POST http://localhost:8081/login
Content-Type: application/json

{
  "userEmail": "zerobase@g.c",
  "password": "1234"
}

###로그인 실패 - 비밀번호 틀림
POST http://localhost:8081/login
Content-Type: application/json

{
  "userEmail": "zerobase@gmail.com",
  "password": "123"
}

###토큰으로 유저 이메일 받아오기
GET http://localhost:8081/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyRW1haWwiOiJ6ZXJvYmFzZUBnbWFpbC5jb20iLCJzdWIiOiJBY2Nlc3NUb2tlbiIsImlhdCI6MTY4MTEwNzQxNSwiZXhwIjoxNjgxMTExMDE1fQ.EKGivco-1MeXF806zdZaOwNVmoxDKUjF6n0LLJukWJ0

###회원정보 수정
PUT localhost:8081/user/detail/modify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyRW1haWwiOiJ6ZXJvYmFzZUBnbWFpbC5jb20iLCJzdWIiOiJBY2Nlc3NUb2tlbiIsImlhdCI6MTY4MTExODEwMywiZXhwIjoxNjgxMTIxNzAzfQ.Dej55zK_cAvSTiru9iQcwk-5KxOZ8OHJjxEar5Rm6d4

{
  "currentPassword" : "1234",
  "updatePassword" : "",
  "username" : "test",
  "phoneNumber" : "01012341234"
}

###리프레시 토큰 사용하여 어세스토큰 갱신
POST http://localhost:8081/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyRW1haWwiOiJ6ZXJvYmFzZUBnbWFpbC5jb20iLCJzdWIiOiJBY2Nlc3NUb2tlbiIsImlhdCI6MTY4MTEwNzQxNSwiZXhwIjoxNjgxMTExMDE1fQ.EKGivco-1MeXF806zdZaOwNVmoxDKUjF6n0LLJukWJ0
Authorization-refresh: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJSZWZyZXNoVG9rZW4iLCJpYXQiOjE2ODExMDc0MTUsImV4cCI6MTY4MjMxNzAxNX0.X-MBwGjQ-B97_73v9SmctLZ5rZitRZocUA6daup7xzk

###회원정보 보기
GET localhost:8081/user/detail
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyRW1haWwiOiJ6ZXJvYmFzZUBnbWFpbC5jb20iLCJzdWIiOiJBY2Nlc3NUb2tlbiIsImlhdCI6MTY4MTExODEwMywiZXhwIjoxNjgxMTIxNzAzfQ.Dej55zK_cAvSTiru9iQcwk-5KxOZ8OHJjxEar5Rm6d4
