###es save
POST http://localhost:8081/search/auction-document/2

###Starting Price
GET http://localhost:8081/search/auctions/starting-price?startingPrice=1000&size=10

###minimumBid
GET http://localhost:8081/search/auctions/minimum-bid?minimumBid=100&size=10

###itemStatus
GET http://localhost:8081/search/auctions/item-status?itemStatus=GOOD&page=1&size=20

###category
GET http://localhost:8081/search/auctions/category?category=BAG&page=1&size=20

###SearchCondition
GET http://localhost:8081/search/auctions?category=ETC&itemStatus=GOOD&size=20

###description match
GET http://localhost:8081/search/auctions/description/matches?description=애플&page=1&size=10

###description contains
GET http://localhost:8081/search/auctions/description/contains?description=iphone&page=0&size=20

###item name
GET localhost:8081/search/auctions/item-name/contain?itemName=프로&sortProperties=STARTING_PRICE&direction=DESC&page=0&size=20

