spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1
    url: jdbc:mariadb://localhost:3306/a_uction
  jwt:
    secret: "p2s5v8y/B?E(H+MbQeThWmZq3t6w9z$C"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

server:
  port: 8081
