jwt:
  access:
    expiration: 3600000 # ACCESS_TOKEN_EXPIRE_TIME = 1000 * 60 * 60
    header: Authorization

  refresh:
    expiration: 1209600000 # REFRESH_TOKEN_EXPIRE_TIME = 1000 * 60 * 60 * 24 * 14
    header: Authorization-refresh


  prefix: "Bearer "